/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as CrewsRouteImport } from './routes/crews'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrewsCreateRouteImport } from './routes/crews_.create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsRoute = CrewsRouteImport.update({
  id: '/crews',
  path: '/crews',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewsCreateRoute = CrewsCreateRouteImport.update({
  id: '/crews_/create',
  path: '/crews/create',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/crews': typeof CrewsRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/signup': typeof SignupRoute
  '/crews/create': typeof CrewsCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/crews': typeof CrewsRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/signup': typeof SignupRoute
  '/crews/create': typeof CrewsCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clubs': typeof ClubsRoute
  '/crews': typeof CrewsRoute
  '/gallery': typeof GalleryRoute
  '/generate': typeof GenerateRoute
  '/signup': typeof SignupRoute
  '/crews_/create': typeof CrewsCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clubs'
    | '/crews'
    | '/gallery'
    | '/generate'
    | '/signup'
    | '/crews/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clubs'
    | '/crews'
    | '/gallery'
    | '/generate'
    | '/signup'
    | '/crews/create'
  id:
    | '__root__'
    | '/'
    | '/clubs'
    | '/crews'
    | '/gallery'
    | '/generate'
    | '/signup'
    | '/crews_/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubsRoute: typeof ClubsRoute
  CrewsRoute: typeof CrewsRoute
  GalleryRoute: typeof GalleryRoute
  GenerateRoute: typeof GenerateRoute
  SignupRoute: typeof SignupRoute
  CrewsCreateRoute: typeof CrewsCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews': {
      id: '/crews'
      path: '/crews'
      fullPath: '/crews'
      preLoaderRoute: typeof CrewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crews_/create': {
      id: '/crews_/create'
      path: '/crews/create'
      fullPath: '/crews/create'
      preLoaderRoute: typeof CrewsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubsRoute: ClubsRoute,
  CrewsRoute: CrewsRoute,
  GalleryRoute: GalleryRoute,
  GenerateRoute: GenerateRoute,
  SignupRoute: SignupRoute,
  CrewsCreateRoute: CrewsCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
